Repository rostikkkk2/uber-landing, pull requests merged in 2018-10, with the labels that each got.

#3 added guarantees and services in home page
  .gitignore
  assets/AppAsset.php
  config/db.php
  controllers/WorkerController.php
  package.json
  views/landing/landing.php
  web/images/1.png
  web/images/2.png
  web/images/3.png
  web/images/4.png
  web/images/5.png
  web/images/6.png
  web/images/7.png
  web/images/8.png
  web/images/guarantees_1.png
  web/images/guarantees_2.png
  web/images/guarantees_3.png
  web/images/guarantees_4.png
  web/images/guarantees_5.png
  web/images/guarantees_6.png
  web/images/guarantees_7.png
  web/images/guarantees_8.png
  web/images/guarantees_9.png
  web/scss/_service.scss
  web/scss/style.scss
Labels: question

#6 Feature/husky
  package-lock.json
  package.json
  sass-lint.config.yml
  web/scss/_header.scss
  web/scss/_home.scss
Labels: finished

#7 added requirement, fix layout files
  config/db.php
  views/landing/faq.php
  views/landing/guarantees.php
  views/landing/landing.php
  views/landing/requirement.php
  views/layouts/basic.php
  web/images/requirements_1.png
  web/images/requirements_2.png
  web/images/requirements_3.png
  web/scss/_home.scss
Labels: finished

#8 add media.scss
  views/landing/faq.php
  views/landing/guarantees.php
  views/landing/landing.php
  views/landing/requirement.php
  web/scss/_home.scss
  web/scss/media.scss
  web/scss/style.scss
Labels: finished

#9 added footer
  views/landing/guarantees.php
  views/layouts/basic.php
  web/images/1.png
  web/images/2.png
  web/images/3.png
  web/images/4.png
  web/images/5.png
  web/images/6.png
  web/images/7.png
  web/images/8.png
  web/images/appstore.png
  web/images/play.png
  web/scss/_footer.scss
  web/scss/_helpers.scss
  web/scss/_home.scss
  web/scss/_variables.scss
  web/scss/style.scss
Labels: finished, reviewed

#11 last fix layout
  views/landing/faq.php
  views/landing/requirement.php
  views/layouts/basic.php
  web/scss/_footer.scss
  web/scss/_helpers.scss
  web/scss/_home.scss
  web/scss/_variables.scss
  web/scss/media.scss
Labels: finished

#12 style header add forms and about us
  assets/AppAsset.php
  config/db.php
  config/web.php
  controllers/LandingController.php
  migrations/m181007_092117_create_new_worker_table.php
  migrations/m181010_222351_create_partner_table.php
  models/ContactForm.php
  models/LoginForm.php
  models/NewWorker.php
  models/Partner.php
  models/User.php
  sass-lint.config.yml
  views/landing/about_us.php
  views/landing/faq.php
  views/landing/guarantees.php
  views/landing/landing.php
  views/landing/requirement.php
  views/layouts/basic.php
  views/layouts/modal-forms/modalFormPartner.php
  views/layouts/modal-forms/modalFormWorker.php
  web/images/about_us.jpeg
  web/images/guarantees_1.png
  web/images/guarantees_2.png
  web/images/guarantees_3.png
  web/images/guarantees_4.png
  web/images/guarantees_5.png
  web/images/guarantees_6.png
  web/images/guarantees_7.png
  web/images/guarantees_8.png
  web/images/guarantees_9.png
  web/images/requirements_1.png
  web/images/requirements_2.png
  web/images/requirements_3.png
  web/js/script.js
  web/scss/_header.scss
  web/scss/_helpers.scss
  web/scss/_home.scss
Labels: finished

#10 Feature/admin
  assets/AppAsset.php
  commands/FackerController.php
  config/web.php
  controllers/ErrorController.php
  controllers/LandingController.php
  migrations/m181007_092117_create_new_worker_table.php
  modules/admin/Module.php
  modules/admin/controllers/DefaultController.php
  modules/admin/controllers/ListController.php
  modules/admin/models/LoginForm.php
  modules/admin/models/User.php
  modules/admin/views/default/login.php
  modules/admin/views/layouts/main.php
  modules/admin/views/list/page.php
  modules/admin/views/list/partner.php
Labels: finished

#14 fix admin, fix layout, add contacts, fix header-footer
  commands/FackerController.php
  config/web.php
  controllers/LandingController.php
  migrations/m181007_092117_create_new_worker_table.php
  migrations/m181010_222351_create_partner_table.php
  models/NewWorker.php
  models/Partner.php
  modules/admin/controllers/ListController.php
  modules/admin/views/list/partner.php
  modules/admin/views/list/worker.php
  views/landing/contacts.php
  views/landing/requirement.php
  views/layouts/basic.php
  web/images/icon-instagram.png
  web/scss/_footer.scss
  web/scss/_header.scss
  web/scss/_home.scss
Labels: finished, reviewed

#15 add not finish fonts
  .gitignore
  assets/AppAsset.php
  config/db.php
  views/landing/about_us.php
  views/landing/contacts.php
  views/landing/faq.php
  views/landing/guarantees.php
  views/landing/requirement.php
  views/layouts/basic.php
  views/layouts/modal-forms/modalFormPartner.php
  views/layouts/modal-forms/modalFormWorker.php
  web/css/fonts/GenR102.ttf
  web/css/fonts/NewBaskervilleC Bold.ttf
  web/scss/_header.scss
  web/scss/_helpers.scss
  web/scss/_home.scss
  web/scss/fonts/GenR102.ttf
  web/scss/fonts/NewBaskervilleC Bold.ttf
  web/scss/style.scss
Labels: finished

#19 fix last
  config/params.php
  config/web.php
  models/NewWorker.php
  models/Partner.php
  modules/admin/controllers/ListController.php
  modules/admin/views/layouts/main.php
  modules/admin/views/list/partner.php
  modules/admin/views/list/worker.php
  views/landing/about_us.php
  views/landing/contacts.php
  views/landing/faq.php
  views/landing/guarantees.php
  views/landing/requirement.php
  web/scss/_header.scss
  web/scss/_home.scss
  web/scss/media.scss
Labels: finished
